# Generated by Django 2.1.8 on 2019-06-26 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documenttype', models.CharField(max_length=50)),
                ('document', models.CharField(max_length=50)),
                ('civilstatus', models.CharField(max_length=50)),
                ('ethnicgroup', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
    ]
