# Generated by Django 2.1.8 on 2019-06-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190624_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='civilstatus',
            field=models.CharField(default='viudo', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='documenttype',
            field=models.CharField(default='TI', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ethnicgroup',
            field=models.CharField(default='rata', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='genre',
            field=models.CharField(default='male', max_length=50),
            preserve_default=False,
        ),
    ]
